events/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),   
]

my_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    
    # # CBV's path for Event model 
    path('events/', views.EventList.as_view(), name='event-index'),
    path('events/<int:event_id>', views.event_detail, name='event-detail'),
    # path('events/<int:pk>', views.EventDetail.as_view(), name='event-detail'),
    path('events/<int:pk>/update/', views.EventUpdate.as_view(), name='event-update'),
    path('events/<int:pk>/delete/', views.EventDelete.as_view(), name='event-delete'),
    path('events/create/', views.EventCreate.as_view(), name='event-create'),
    
    path('features/', views.FeatureList.as_view(), name='feature-index'),
    path('features/<int:pk>', views.FeatureDetail.as_view(), name='feature-detail'),
    path('features/<int:pk>/update/', views.FeatureUpdate.as_view(), name='feature-update'),
    path('features/<int:pk>/delete/', views.FeatureDelete.as_view(), name='feature-delete'),
    path('features/create/', views.FeatureCreate.as_view(), name='feature-create'),

    path('events/<int:event_id>/add-room/', views.add_room, name='add-room'),

    path('events/<int:event_id>/associate-feature/<int:feature_id>/', views.associate_feature, name='associate-feature'),
    path('events/<int:event_id>/remove-feature/<int:feature_id>/', views.remove_feature, name='remove-feature'),
    path('accounts/signup/', views.signup, name='signup'),
]

my_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date

ROOMS = (
    ('H1', 'Hall 1'),
    ('H2', 'Hall 2'),
    ('H3', 'Hall 3'),
    ('H4', 'Hall 4'),
    ('H5', 'Hall 5'),
    ('H6', 'Hall 6'),
)

# Create your models here.
class Feature(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField(max_length=250)
    color = models.CharField(max_length=20)
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('feature-detail', kwargs={'pk': self.id})

class Event(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField(max_length=250)
    features = models.ManyToManyField(Feature)
    date = models.DateField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return f"{self.title} ON {self.date}"

    def get_absolute_url(self):
        return reverse('event-detail', kwargs={'pk': self.id})

class Room(models.Model):
    date = models.DateField()
    room = models.CharField(
        max_length=2,
        choices=ROOMS,
        default=ROOMS[0][0]
    )
    event = models.ForeignKey(Event, on_delete = models.CASCADE)

    def __str__(self):
        return f"{self.event} : {self.get_room_display()} on {self.date}"
    
    class Meta:
        ordering = ['-date']

my_app/forms.py
from django import forms
from .models import Room

class RoomForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = ['date', 'room']
        widgets = {
            'date': forms.DateInput(
                format=('%Y-%m-%d'),
                attrs={
                    'placeholder': 'Select a date',
                    'type': 'date'
                }
            ),
        }

my_app/views.py
from django.shortcuts import render, redirect
from .models import Event, Feature, Room
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import RoomForm
from django.contrib.auth.views import LoginView

# Create your views here.
# Events classes
class Home(LoginView):
    template_name = 'home.html'

class EventList(LoginRequiredMixin, ListView):
    model = Event

# class EventDetail(LoginRequiredMixin, DetailView):
#     features = Feature.objects.all()
#     # event = Event.objects.all()
#     # toys_cat_doesnt_have = Feature.objects.exclude(id__in = event.features.all().values_list('id'))
#     room_form = RoomForm()
#     model = Event

@login_required
def event_detail(request, event_id):
    event = Event.objects.get(id=event_id)
    features = Feature.objects.all()
    features_event_doesnt_have = Feature.objects.exclude(id__in = event.features.all().values_list('id'))
    room_form = RoomForm()
    return render(request, 'my_app/event_detail.html', {'event': event, 'room_form': room_form, 'features': features_event_doesnt_have})

class EventUpdate(LoginRequiredMixin, UpdateView):
    model = Event
    fields = ['title', 'description', 'date']

class EventDelete(LoginRequiredMixin, DeleteView):
    model = Event
    success_url = '/events/'

class EventCreate(LoginRequiredMixin, CreateView):
    model = Event
    fields = ['title', 'description', 'date']

    def form_valid(self, form):
        # Assign the logged in user (self.request.user)
        form.instance.user = self.request.user  # form.instance is the cat
        # Let the CreateView do its job as usual
        return super().form_valid(form)

# Features classes
class FeatureList(LoginRequiredMixin, ListView):
    model = Feature

class FeatureDetail(LoginRequiredMixin, DetailView):
    model = Feature

class FeatureUpdate(LoginRequiredMixin, UpdateView):
    model = Feature
    fields = ['title', 'description', 'color']

class FeatureDelete(LoginRequiredMixin, DeleteView):
    model = Feature
    success_url = '/features/'

class FeatureCreate(LoginRequiredMixin, CreateView):
    model = Feature
    fields = ['title', 'description', 'color']

def signup(request):
    error_message = ''
    if request.method == 'POST':
        # This is how to create a 'user' form object
        # that includes the data from the browser
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # This will add the user to the database
            user = form.save()
            # This is how we log a user in
            login(request, user)
            return redirect('event-index')
        else:
            error_message = 'Invalid sign up - try again'
    # A bad POST or a GET request, so render signup.html with an empty form
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'signup.html', context)
    # Same as: 
    # return render(
    #     request, 
    #     'signup.html',
    #     {'form': form, 'error_message': error_message}
    # )

@login_required
def add_room(request, event_id):
    form = RoomForm(request.POST)
    if form.is_valid():
        new_room = form.save(commit=False)
        new_room.event_id = event_id
        new_room.save()
    return redirect('event-detail', event_id=event_id)

@login_required
def associate_feature(request, event_id, feature_id):
    Event.objects.get(id=event_id).features.add(feature_id)
    return redirect('event-detail', event_id=event_id)

@login_required
def remove_feature(request, event_id, feature_id):
    event = Event.objects.get(id=event_id)
    feature = Feature.objects.get(id=feature_id)
    event.features.remove(feature)
    return redirect('event-detail', event_id=event.id)

my_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" type="image/png" href="{% static 'images/splash.svg' %}" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}" />
    <title>Events</title>
    {% block head %}

    {% endblock %}
  </head>
  <body>
    <header>
      <div class="header-logo-container">
        <a href="{% url 'home' %}"><img src="{% static 'images/header-logo.svg' %}" alt="The Events Logo" /></a>
      </div>
      <nav>
        <ul>
          {% if user.is_authenticated %}
            <li>
              <a href="{% url 'event-index' %}">All Events</a>
            </li>
            <li>
              <a href="{% url 'event-create' %}">Add Event</a>
            </li>
            <li>
              <a href="{% url 'feature-index' %}">All Features</a>
            </li>
            <li>
              <a href="{% url 'feature-create' %}">Add Feature</a>
            </li>
            <li>
              <form id="logout-form" method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button type="submit">Log out</button>
              </form>
            </li>
          {% else %}
            <li>
              <a href="{% url 'home' %}">Login</a>
            </li>
            <li>
              <a href="{% url 'signup' %}">Sign Up</a>
            </li>
          {% endif %}
        </ul>
      </nav>
    </header>
    <main>
      {% block content %}

      {% endblock %}
    </main>
  </body>
</html>

my_app/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" href="{% static 'css/home.css' %}" />
{% endblock %}
{% block content %}
  <section class="logo-container">
    <div class="cat-container">
      <img src="{% static 'images/splash.svg' %}" alt="events" />
    </div>
    <img src="{% static 'images/logotype.svg' %}" alt="The Events" />
  </section>

  {% if not user.is_authenticated %}
    <section>
      <form action="{% url 'home' %}" method="post" class="login">
        <h1>Login</h1>
        {% csrf_token %} {{ form.as_p }}
        <input type="hidden" name="next" value="{{ next }}" />
        <button type="submit" class="btn submit">Login</button>
      </form>
    </section>
  {% endif %}
{% endblock %}

my_app/templates/my_app/event_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <div class="page-header">
    <h1>Delete Event?</h1>
    <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer" />
  </div>
  <h2>Are you sure you want to delete {{ object.title }}?</h2>

  <form action="" method="post" class="form">
    {% csrf_token %}
    <a href="{% url 'event-detail' event.id %}" class="btn secondary">Cancel</a>
    <button type="submit" class="btn danger">Yes - Delete!</button>
  </form>
{% endblock %}

my_app/templates/my_app/event_detail.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" href="{% static 'css/cats/cat-detail.css' %}" />
  <link href="https://cdn.jsdelivr.net/npm/mc-datepicker/dist/mc-calendar.min.css" rel="stylesheet" />
  <link rel="stylesheet" href="{% static 'css/mcdp.css' %}" />
  <!-- MCDatepicker JS -->
  <script src="https://cdn.jsdelivr.net/npm/mc-datepicker/dist/mc-calendar.min.js"></script>
  <!-- Existing CSS -->
  <link rel="stylesheet" href="{% static 'css/cats/cat-detail.css' %}" />
  <script defer src="{% static 'js/cat-detail.js' %}"></script>
{% endblock %}
{% block content %}
  <section class="cat-container">
    <div class="cat-img">
      <img src="{% static 'images/sk8r-boi-cat.svg' %}" alt="A skater boy cat" />
    </div>
    <div class="cat-details">
      <h1>{{ event.title }}</h1>
      <h3>{{ event.date }}</h3>
      <p>{{ event.description }}</p>

      <div class="cat-actions">
        <a href="{% url 'event-update' event.id %}" class="btn warn">Edit</a>
        <a href="{% url 'event-delete' event.id %}" class="btn danger">Delete</a>
      </div>
    </div>
  </section>

  <div class="feedings-toy-container">
    <section class="feedings">
      <div class="subsection-title">
        <h2>Rooms</h2>
        <img src="{% static 'images/cat-cone.svg' %}" alt="An ice cream cone cat" />
        <img src="{% static 'images/cat-onigiri.svg' %}" alt="A cat as onigiri" />
        <img src="{% static 'images/kitty-kabob.svg' %}" alt="A kabob of kittens" />
      </div>

      <h3>Add a Room</h3>
      <form action="{% url 'add-room' event.id %}" method="post" class="subsection-content" autocomplete="off">
        {% csrf_token %}
        {{ room_form.as_p }}
        <button type="submit" class="btn submit">Add Room</button>
      </form>

      <br /><br />
      <h3>Past Rooms</h3>
      {% if event.room_set.all.count %}
        <table>
          <thead>
            <tr>
              <th>Date</th>
              <th>Room</th>
            </tr>
          </thead>
          <tbody>
            {% for room in event.room_set.all %}
              <tr>
                <td>{{ room.date }}</td>
                <td>{{ room.get_room_display }}</td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      {% else %}
        <div class="subsection-content">
          <p>⚠️ {{ event.title }} has no room!</p>
        </div>
      {% endif %}
    </section>

    <section class="toys">
      <div class="subsection-title">
        <h2>Features</h2>
        <img src="{% static 'images/string.svg' %}" alt="A ball of string" />
        <img src="{% static 'images/mouse.svg' %}" alt="A mouse" />
        <img src="{% static 'images/fish.svg' %}" alt="A fishy toy" />
      </div>
      <h3>{{ event.title }}'s Features</h3>
      <div class="subsection-content">
        {% if event.features.count %}
          {% for feature in event.features.all %}
            <div class="toy-container">
              <div class="color-block" style="background-color: {{ feature.color }}"></div>
              <a href="{% url 'feature-detail' feature.id %}"><p>{{ feature.title }}</p></a>
              <form action="{% url 'remove-feature' event.id feature.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Remove Feature</button>
              </form>
            </div>
          {% endfor %}
        {% else %}
          <p class="no-toys">{{ event.title }} doesn't have any feature!</p>
        {% endif %}
      </div>

      <h3>Available Features</h3>
      <div class="subsection-content">
        {% if features.count %}
          {% for feature in features.all %}
            <div class="toy-container">
              <div class="color-block" style="background-color: {{ feature.color }}"></div>
              <a href="{% url 'feature-detail' feature.id %}"><p>{{ feature.title }}</p></a>
              <form action="{% url 'associate-feature' event.id feature.id %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn submit">Add Feature</button>
              </form>
            </div>
          {% endfor %}
        {% else %}
          <p class="all-toys">{{ event.title }} already has all the available features 🥳</p>
        {% endif %}
      </div>
    </section>
  </div>
{% endblock %}

my_app/templates/my_app/event_form.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" href="{% static 'css/form.css' %}" />
  <link href="https://cdn.jsdelivr.net/npm/mc-datepicker/dist/mc-calendar.min.css" rel="stylesheet" />
  <link rel="stylesheet" href="{% static 'css/mcdp.css' %}" />
  <!-- MCDatepicker JS -->
  <script src="https://cdn.jsdelivr.net/npm/mc-datepicker/dist/mc-calendar.min.js"></script>
  <!-- Existing CSS -->
  <link rel="stylesheet" href="{% static 'css/cats/cat-detail.css' %}" />
  <script defer src="{% static 'js/cat-detail.js' %}"></script>

{% endblock %}
{% block content %}
  <div class="page-header">
    {% if object %}
      <h1>Edit {{ object.name }}</h1>
    {% else %}
      <h1>Add Event</h1>
    {% endif %}
    <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer" />
  </div>

  <form action="" method="post" class="form-container">
    {% csrf_token %}
    <table>{{ form.as_table }}</table>
    <button type="submit" class="btn submit">Submit!</button>
  </form>
{% endblock %}

my_app/templates/my_app/event_list.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" href="{% static 'css/cats/cat-index.css' %}" />
{% endblock %}
{% block content %}
  <section class="page-header">
    <h1>Event List</h1>
    <img src="{% static 'images/cool-cat.svg' %}" alt="A cool cat" />
    <img src="{% static 'images/happy-cat.svg' %}" alt="A happy cat" />
    <img src="{% static 'images/teacup-cat.svg' %}" alt="A cat in a teacup" />
    <img src="{% static 'images/cat-in-box.svg' %}" alt="A cat in a box" />
  </section>

  <section class="card-container">
    {% for event in event_list %}
      <div class="card">
        {% comment %} <a href="/cat-detail/{{ cat.id }}"> {% endcomment %}
        <a href="{% url 'event-detail' event.id %}">
          <div class="card-content">
            <div class="card-img-container">
              <img src="{% static 'images/sk8r-boi-cat.svg' %}" alt="A skater boy cat" />
            </div>
            <h2 class="card-title">{{ event.title }}</h2>
            <p><small>{{ event.description }}</small></p>
          </div>
        </a>
      </div>
    {% endfor %}
  </section>
{% endblock %}

my_app/templates/my_app/feature_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <div class="page-header">
    <h1>Delete Feature?</h1>
    <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer" />
  </div>
  <h2>Are you sure you want to delete {{ object.name }}?</h2>

  <form action="" method="post" class="form">
    {% csrf_token %}
    <a href="{% url 'feature-detail' feature.id %}" class="btn secondary">Cancel</a>
    <button type="submit" class="btn danger">Yes - Delete!</button>
  </form>
{% endblock %}

my_app/templates/my_app/feature_detail.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" href="{% static 'css/toys/toy-detail.css' %}" />
{% endblock %}
{% block content %}
  <div class="card" style="border-color: {{ feature.color }}">
    <div class="card-bg" style="background-color: {{ feature.color }}"></div>
    <div class="card-content">
      <h2>{{ feature.title }}</h2>
      <p>{{ feature.description }}</p>
    </div>
  </div>
  <a href="{% url 'feature-update' feature.id %}" class="btn warn">Edit</a>
  <a href="{% url 'feature-delete' feature.id %}" class="btn danger">Delete</a>
{% endblock %}

my_app/templates/my_app/feature_form.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %}
{% block content %}
  <div class="page-header">
    {% if object %}
      <h1>Edit {{ object.name }}</h1>
    {% else %}
      <h1>Add Feature</h1>
    {% endif %}
    <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer" />
  </div>
  <form action="" method="post" class="form-container" autocomplete="off">
    {% csrf_token %}
    <table>{{ form.as_table }}</table>
    <button type="submit" class="btn submit">Submit!</button>
  </form>
{% endblock %}

my_app/templates/my_app/feature_list.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" href="{% static 'css/toys/toy-index.css' %}" />
{% endblock %}
{% block content %}
  <section class="page-header">
    <h1>All Events Rooms</h1>
    <img src="{% static 'images/string.svg' %}" alt="A ball of string" />
    <img src="{% static 'images/mouse.svg' %}" alt="A mouse" />
    <img src="{% static 'images/post.svg' %}" alt="A scratching post" />
    <img src="{% static 'images/fish.svg' %}" alt="A fishy toy" />
  </section>

  <section class="card-container">
    {% for feature in feature_list %}
      <div class="card" style="border-color: {{ feature.color }}">
        <div class="card-bg" style="background-color: {{ feature.color }}"></div>
        <a href="{% url 'feature-detail' feature.id %}">
          <div class="card-content">
            <h2>{{ feature.title }}</h2>
            <p>{{ feature.description }}</p>
          </div>
        </a>
      </div>
    {% endfor %}
  </section>
{% endblock %}

my_app/templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %}
{% block content %}
  <div class="page-header">
    <h1>Sign Up</h1>
    <img src="{% static 'images/nerd-cat.svg' %}" alt="A cat using a computer" />
  </div>
  {% if error_message %}
    <p class="red-text">{{ error_message }}</p>
  {% endif %}
  <form action="" method="post" class="form-container" autocomplete="off">
    {% csrf_token %}
    <table>{{ form.as_table }}</table>
    <button type="submit" class="btn submit">Submit!</button>
  </form>
{% endblock %}